apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: msname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msname
  template:
    metadata:
      labels:
        app: msname
    spec:      
      containers:
      - image: nebulaeproject_context/msname.backend.backendname:0.0.1
        name: backendname
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        resources:
          requests:
            cpu: "50m"
        env:     
        # EVENT STORE CONFIG 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        # INTERNAL MONGO DB CONFIG
        - name: MONGODB_URL
          value: mongodb://msshortname-mongo:27017
        - name: MONGODB_DB_NAME
          value: msdbname
        # JWT CONGIF        
        - name: JWT_PUBLIC_KEY
          value: -----BEGIN PUBLIC KEY-----\n\n-----END PUBLIC KEY-----
        # API - APIID CONFIG
        - name: APIID_REPLIES_TOPIC_SUBSCRIPTION
          value: apiid-replies-topic-mbe-backendname
        - name: REPLY_TIMEOUT
          value: '2000'
        - name: BROKER_TYPE
          value: PUBSUB
        # RESET LOCK INITIALIZE BACKED
        - name: LOCKVERSION
          value: "initial_lock"
        
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
      